
[default]
access_key = ACCESS_KEY
secret_key = SECRET_KEY
access_token = ACCESS_TOKEN
check_ssl_hostname = False
encoding = UTF-8
encrypt = False
guess_mime_type = True
host_base = s3inbox:8000
host_bucket = s3inbox:8000
human_readable_sizes = true
multipart_chunk_size_mb = 50
use_https = False
socket_timeout = 30
